// autogenerated turbo fused MMA instance for asymmetric GGML_TYPE_TURBO8_0 K / GGML_TYPE_F16 V
// (f16<->t8 VBR entry band: closes the materialize penalty during the f16->t8 degrade)

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 8, 8, GGML_TYPE_TURBO8_0, GGML_TYPE_F16);
