// autogenerated turbo fused MMA instance for asymmetric TURBO3_TCQ K / TURBO4_0 V (dynamic VBR adjacent-tier pair)

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 32, 1, GGML_TYPE_TURBO3_TCQ, GGML_TYPE_TURBO4_0);
