// autogenerated turbo fused MMA instance for asymmetric TURBO2_TCQ K / TURBO1_TCQ V (dynamic VBR adjacent-tier pair)

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 1, 8, GGML_TYPE_TURBO2_TCQ, GGML_TYPE_TURBO1_TCQ);
