// autogenerated turbo fused MMA instance for asymmetric TURBO4_0 K / TURBO8_0 V (dynamic VBR adjacent-tier pair)

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 16, 2, GGML_TYPE_TURBO4_0, GGML_TYPE_TURBO8_0);
